service: core

provider:
  name: aws
  region: eu-central-1
  runtime: nodejs16.x
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Resource: "arn:aws:s3:::assets.ts-ai-kitkhe.ge"
          Action: "s3:*"
        - Effect: "Allow"
          Resource: "arn:aws:s3:::assets.ts-ai-kitkhe.ge/*"
          Action: "s3:*"

custom:
  # Dynamo DBs
  DYNAMO_DB_BOOKS_TABLE_NAME: books
  # Plugins
  bundle:
    sourcemaps: false # Enable source maps
    caching: false # Enable Webpack caching
    concurrency: 2 # Set desired concurrency, defaults to the number of available cores
    packager: yarn # Specify a packager, 'npm' or 'yarn'. Defaults to 'npm'.

functions:
  getSignedUrl:
    handler: functions/get-signed-url/handler.main
    environment:
      AWS_BUCKET_NAME: assets.ts-ai-kitkhe.ge
    events:
      - httpApi:
          method: POST
          path: /test

resources:
  Resources:
    booksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.DYNAMO_DB_BOOKS_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-bundle
