service: ml

provider:
  name: aws
  region: eu-central-1
  runtime: python3.8
  versionFunctions: false
  ecr:
    scanOnPush: false
    images:
      s3ImageProcessor:
        path: ./functions/process-image
  iam:
    role:
      statements:
        - Effect: "Allow"
          Resource:
            - "arn:aws:s3:::assets.ts-ai-kitkhe.ge/*"
          Action: "s3:*"

functions:
  hello:
    handler: functions.hello-world.handler.hello

  processImage:
    image: s3ImageProcessor
    timeout: 900
    events:
      - s3:
          bucket: assets.ts-ai-kitkhe.ge
          event: s3:ObjectCreated:*
          existing: true

  generateText:
    handler: functions.generate-text.handler.main