service: ml

custom:
  # S3
  S3_ASSETS_BUCKET_NAME: assets.ts-ai-kitkhe.ge
  S3_ML_BUCKET_NAME: ml.ts-ai-kitkhe.ge
  # Lambda
  CORE_PAGES_GET_ALL_LAMBDA_ARN: ${cf:core-${self:provider.stage}.PagesGetAllLambdaArn}

provider:
  name: aws
  region: eu-central-1
  runtime: python3.8
  versionFunctions: false
  ecr:
    scanOnPush: false
    images:
      s3ImageProcessor:
        path: ./functions/process-image
      generateText:
        path: ./functions/generate-text
  iam:
    role:
      statements:
        - Effect: "Allow"
          Resource:
            - "arn:aws:s3:::${self:custom.S3_ASSETS_BUCKET_NAME}"
            - "arn:aws:s3:::${self:custom.S3_ASSETS_BUCKET_NAME}/*"
            - "arn:aws:s3:::${self:custom.S3_ML_BUCKET_NAME}"
            - "arn:aws:s3:::${self:custom.S3_ML_BUCKET_NAME}/*"
          Action: "s3:*"

functions:
  processImage:
    image: s3ImageProcessor
    timeout: 900
    environment:
      S3_ML_BUCKET_NAME: ${self:custom.S3_ML_BUCKET_NAME}
    events:
      - eventBridge:
          pattern:
            source:
              - aws.s3
            detail-type:
              - Object Created
            detail:
              bucket:
                name:
                  - ${self:custom.S3_ASSETS_BUCKET_NAME}
              object:
                key:
                  - prefix: "books/"

  generateText:
    image: generateText
    timeout: 90
    environment:
      S3_ML_BUCKET_NAME: ${self:custom.S3_ML_BUCKET_NAME}
    events:
      - eventBridge:
          pattern:
            source:
              - aws.s3
            detail-type:
              - Object Created
            detail:
              bucket:
                name:
                  - ${self:custom.S3_ML_BUCKET_NAME}
              object:
                key:
                  - prefix: "books/"

  concatenateText:
    handler: functions.concatenate-text.handler.main
    timeout: 90
    environment:
      S3_ML_BUCKET_NAME: ${self:custom.S3_ML_BUCKET_NAME}
      CORE_PAGES_GET_ALL_LAMBDA_ARN: ${self:custom.CORE_PAGES_GET_ALL_LAMBDA_ARN}
    events:
      - eventBridge:
          pattern:
            source:
              - aws.s3
            detail-type:
              - Object Created
            detail:
              bucket:
                name:
                  - ${self:custom.S3_ML_BUCKET_NAME}
              object:
                key:
                  - prefix: "books/"
      - eventBridge:
          pattern:
            source:
              - aws.s3
            detail-type:
              - Object Deleted
            detail:
              bucket:
                name:
                  - ${self:custom.S3_ML_BUCKET_NAME}
              object:
                key:
                  - prefix: "books/"

  predictionsUpdate:
    handler: functions.predictions-update.handler.main
    events:
      - httpApi:
          method: post
          path: /book/{bookId}/pages/{pageId}/predictions

plugins:
  - serverless-python-requirements
